# Server
server.port=${PORT:8080}

# PostgreSQL - Supabase
spring.datasource.url=jdbc:postgresql://db.jmstcrknwtfjegmyguvh.supabase.co:5432/postgres?user=postgres&password=LUsdUXzClAlIoy1M&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ELO defaults
ranking.elo.initial-rating=1400
ranking.elo.k-factor=32